version: "3.9"

services:
  db:
    image: postgres:16
    container_name: api-testing-platform-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gurnoor15
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api-testing-platform
    depends_on:
      - db
      - selenium
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:gurnoor15@db:5432/tasks_db
      TEST_DATABASE_URL: sqlite:///./test_app.db
      REPORT_API_URL: http://localhost:8000/test-runs
      BACKEND_URL: http://localhost:8000
      FRONTEND_URL: http://host.docker.internal:5173
      SELENIUM_URL: http://selenium:4444

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: api-testing-platform-selenium
    ports:
      - "4444:4444"
    shm_size: 2gb
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: